bases:
- ../base
resources:
- ingress.yaml
- ldap.yaml
images:
- name: quay.io/parados/workflow-service:latest
  newTag: test

- name: quay.io/parados/notification-service:latest
  newTag: test

configMapGenerator:
- name: ldif-config
  files:
  - test-server.ldif
